name: Pull request checks

on:
  push:
    paths:
      - '.github/**' # Skip unncessary builds
    branches:
      - master  # This triggers the workflow on push to the master branch
  workflow_dispatch:  # This allows the workflow to be triggered manually
  pull_request: # Trigger when pull request is opened targeting master
    paths:
      - '.github/**' # Skip unncessary builds
    branches:
      - master

jobs:
  create-onnx-runtime-artifact:
    uses: ./.github/workflows/create-onnx-runtime-artifact.yml